[locations.0]
sticks = [
  { x = 600.0, y = -450.0 },
  { x = 650.0, y = -475.0 },
  { x = 700.0, y = -400.0 },
  { x = -450.0, y = -200.0 },
  { x = -475.0, y = -250.0 },
  { x = -500.0, y = -225.0 },
]
trees = [
  { x = 0.0, y = -200.0 },
  { x = -100.0, y = -300.0 },
  { x = 100.0, y = -260.0 },
]
berry_bushes = [
  { x = -250.0, y = 400.0 },
  { x = -275.0, y = 350.0 },
  { x = -350.0, y = 300.0 },
  { x = -400.0, y = 375.0 },
]
water_pools = [{ x = 700.0, y = 400.0 }]
change_location_zones = [{ x = 0.0, y = 500.0, connected_location = 1 }]

[locations.1]
trees = [
  { x = 0.0, y = -200.0 },
  { x = -100.0, y = -300.0 },
  { x = 100.0, y = -260.0 },
]
change_location_zones = [{ x = 0.0, y = 500.0, connected_location = 0 }]
